"""alter_parametro_detalle

Revision ID: 1214ae9a3ebe
Revises: 4c49330b4c7e
Create Date: 2022-11-08 08:36:03.400668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1214ae9a3ebe'
down_revision = '4c49330b4c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parametro_detalle', sa.Column('grupo_id', sa.Integer(), nullable=True))
    op.add_column('parametro_detalle', sa.Column('sub_grupo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parametro_detalle', 'grupo', ['grupo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'parametro_detalle', 'sub_grupo', ['sub_grupo_id'], ['id'], ondelete='CASCADE')
    op.drop_column('parametro_detalle', 'subgrupo')
    op.drop_column('parametro_detalle', 'grupo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parametro_detalle', sa.Column('grupo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('parametro_detalle', sa.Column('subgrupo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parametro_detalle', type_='foreignkey')
    op.drop_constraint(None, 'parametro_detalle', type_='foreignkey')
    op.drop_column('parametro_detalle', 'sub_grupo_id')
    op.drop_column('parametro_detalle', 'grupo_id')
    # ### end Alembic commands ###
