"""alter_table_menu

Revision ID: 86a0591be625
Revises: 1214ae9a3ebe
Create Date: 2022-11-10 08:10:47.238678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a0591be625'
down_revision = '1214ae9a3ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('titulo', sa.String(length=50), nullable=False))
    op.add_column('menu', sa.Column('tipo', sa.Integer(), nullable=False))
    op.add_column('menu', sa.Column('icono', sa.String(length=50), nullable=True))
    op.add_column('menu', sa.Column('url', sa.String(length=50), nullable=True))
    op.drop_column('menu', 'nombre')
    op.drop_column('menu', 'estado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('estado', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('nombre', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    op.drop_column('menu', 'url')
    op.drop_column('menu', 'icono')
    op.drop_column('menu', 'tipo')
    op.drop_column('menu', 'titulo')
    # ### end Alembic commands ###
