version: "3.8"
services:
  backend:
    container_name: tarificador_backend_dev
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade heads && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    networks:
      - dev-network

networks:
  dev-network:
    name: dev-network
    driver: bridge