version: "3.8"
services:
  api:
    container_name: groups
    build:
      context: ./
      dockerfile: Dockerfile
      # alembic upgrade heads && 
    command: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8002"
    ports:
      - 8002:8002
    networks:
      - dev-network

networks:
  dev-network:
    name: dev-network
    driver: bridge